name: CI

on:
  push:
    branches:
      - main
      - dev/*
      - feature/*
      - hotfix/*
      - release/*

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Install Dependencies
      #   run: npm install
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

      # - name: Run Tests
      #   run: npm run test

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
